server:
  host: "0.0.0.0"
  port: ":8090"
  base_path: "/api-auth"

database:
  host: "db"
  port: "5432"
  driver: "postgres"
  connection_string: "postgresql://postgres:postgres@db:5432/mydb?sslmode=disable"

jwt:
  secret_key: "8fb90cf688f1f46a5a59711b9a8804c441e86513b7909fefb1b8abfc78aa500c"
  access_token_ttl: "5m"
  refresh_token_ttl: "10h"

webhook:
  url: "https://webhook.site/673e03a4-b1bb-4546-88fa-9a521c61a1d0"