version: '3.8'

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8090:8090"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./config-docker.yaml:/config.yaml
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata: